# Generated by Django 3.0.6 on 2020-05-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do cliente', max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', models.IntegerField(max_length=20)),
            ],
        ),
    ]
